<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>VoSharp.Ike</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VoSharp.Common\VoSharp.Common.csproj" />
    <ProjectReference Include="..\VoSharp.Ipsec\VoSharp.Ipsec.csproj" />
  </ItemGroup>

</Project>
